#!/bin/bash
set -eu

if [ "$DOCKERFILE_PATH" = "" ]; then
    BUILDARGS=""
else
    BUILDARGS="-f $DOCKERFILE_PATH"
fi

docker build --build-arg MICROSCANNER_TOKEN=ZjNmOTA5OTRhZTlk $BUILDARGS -t $IMAGE_NAME .
